### ISSUE TITLE
PPAify flask_talisman

### ISSUE THREAD

**Issue by doismellburning** [SRCF/control-panel#5]
My understanding is that current SRCF policy encourages installing Python dependencies from Ubuntu packages.

`control-panel` depends on [flask_talisman](https://pypi.org/project/flask-talisman/) which is currently installed on `pip.srcf` via pip - it would be convenient if this were in a PPA please

(See also #4)

**Comment by mas90** [comment]
Done: https://launchpad.net/~malcscott/+archive/ubuntu/flask-talisman
